version: "3.9"
services:
  app:
    image: flask_app
    platform: linux/amd64
  db:
    image: postgres
    platform: linux/amd64
    environment:
    - POSTGRES_USER=flask_app
    - POSTGRES_PASSWORD=flask_app_password
    - POSTGRES_USER=flask_app_db
    ports:
    - 5433:5432