version: "3.9"

services:
  app:
    image: $IMAGE_TAG:$GITHUB_REF_NAME-$GITHUB_RUN_ID #flask_app
    platform: linux/amd64
    ports:
      - "25000:8080"
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    platform: linux/amd64